application:
  name: todo-app
server:
  port: 8081
spring:
  data:
    mongodb:
      database: ${APP_DB_MONGO_NAME:todoAppDB}
      host: ${APP_DB_MONGO_HOST:localhost}
      port: ${APP_DB_MONGO_PORT:27017}